// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beer.proto

/*
Package beer is a generated protocol buffer package.

It is generated from these files:
	beer.proto

It has these top-level messages:
	Empty
	Beer
	Cellar
	BeerCellar
*/
package beer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Beer struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DrinkDate int64  `protobuf:"varint,2,opt,name=drink_date,json=drinkDate" json:"drink_date,omitempty"`
	Size      string `protobuf:"bytes,3,opt,name=size" json:"size,omitempty"`
}

func (m *Beer) Reset()                    { *m = Beer{} }
func (m *Beer) String() string            { return proto.CompactTextString(m) }
func (*Beer) ProtoMessage()               {}
func (*Beer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Beer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Beer) GetDrinkDate() int64 {
	if m != nil {
		return m.DrinkDate
	}
	return 0
}

func (m *Beer) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

type Cellar struct {
	Name  string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Beers []*Beer `protobuf:"bytes,2,rep,name=beers" json:"beers,omitempty"`
}

func (m *Cellar) Reset()                    { *m = Cellar{} }
func (m *Cellar) String() string            { return proto.CompactTextString(m) }
func (*Cellar) ProtoMessage()               {}
func (*Cellar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cellar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cellar) GetBeers() []*Beer {
	if m != nil {
		return m.Beers
	}
	return nil
}

type BeerCellar struct {
	Name          string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SyncTime      int64     `protobuf:"varint,2,opt,name=syncTime" json:"syncTime,omitempty"`
	UntappdKey    string    `protobuf:"bytes,3,opt,name=untappdKey" json:"untappdKey,omitempty"`
	UntappdSecret string    `protobuf:"bytes,4,opt,name=untappdSecret" json:"untappdSecret,omitempty"`
	Cellars       []*Cellar `protobuf:"bytes,5,rep,name=cellars" json:"cellars,omitempty"`
}

func (m *BeerCellar) Reset()                    { *m = BeerCellar{} }
func (m *BeerCellar) String() string            { return proto.CompactTextString(m) }
func (*BeerCellar) ProtoMessage()               {}
func (*BeerCellar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BeerCellar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BeerCellar) GetSyncTime() int64 {
	if m != nil {
		return m.SyncTime
	}
	return 0
}

func (m *BeerCellar) GetUntappdKey() string {
	if m != nil {
		return m.UntappdKey
	}
	return ""
}

func (m *BeerCellar) GetUntappdSecret() string {
	if m != nil {
		return m.UntappdSecret
	}
	return ""
}

func (m *BeerCellar) GetCellars() []*Cellar {
	if m != nil {
		return m.Cellars
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "beer.Empty")
	proto.RegisterType((*Beer)(nil), "beer.Beer")
	proto.RegisterType((*Cellar)(nil), "beer.Cellar")
	proto.RegisterType((*BeerCellar)(nil), "beer.BeerCellar")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BeerCellarService service

type BeerCellarServiceClient interface {
	AddBeer(ctx context.Context, in *Beer, opts ...grpc.CallOption) (*Cellar, error)
	GetBeer(ctx context.Context, in *Beer, opts ...grpc.CallOption) (*Beer, error)
}

type beerCellarServiceClient struct {
	cc *grpc.ClientConn
}

func NewBeerCellarServiceClient(cc *grpc.ClientConn) BeerCellarServiceClient {
	return &beerCellarServiceClient{cc}
}

func (c *beerCellarServiceClient) AddBeer(ctx context.Context, in *Beer, opts ...grpc.CallOption) (*Cellar, error) {
	out := new(Cellar)
	err := grpc.Invoke(ctx, "/beer.BeerCellarService/AddBeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerCellarServiceClient) GetBeer(ctx context.Context, in *Beer, opts ...grpc.CallOption) (*Beer, error) {
	out := new(Beer)
	err := grpc.Invoke(ctx, "/beer.BeerCellarService/GetBeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BeerCellarService service

type BeerCellarServiceServer interface {
	AddBeer(context.Context, *Beer) (*Cellar, error)
	GetBeer(context.Context, *Beer) (*Beer, error)
}

func RegisterBeerCellarServiceServer(s *grpc.Server, srv BeerCellarServiceServer) {
	s.RegisterService(&_BeerCellarService_serviceDesc, srv)
}

func _BeerCellarService_AddBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Beer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerCellarServiceServer).AddBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beer.BeerCellarService/AddBeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerCellarServiceServer).AddBeer(ctx, req.(*Beer))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerCellarService_GetBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Beer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerCellarServiceServer).GetBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beer.BeerCellarService/GetBeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerCellarServiceServer).GetBeer(ctx, req.(*Beer))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeerCellarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beer.BeerCellarService",
	HandlerType: (*BeerCellarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBeer",
			Handler:    _BeerCellarService_AddBeer_Handler,
		},
		{
			MethodName: "GetBeer",
			Handler:    _BeerCellarService_GetBeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beer.proto",
}

func init() { proto.RegisterFile("beer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x57, 0x63, 0xc6, 0x07, 0x38, 0xa7, 0xa5, 0xa0, 0x84, 0xf5, 0x41, 0x4e, 0x3d,
	0xd4, 0xbb, 0xe0, 0x0b, 0x11, 0x6f, 0xa9, 0xf7, 0x92, 0x66, 0xe7, 0xb0, 0xd8, 0xa4, 0x61, 0xb3,
	0x0a, 0xf1, 0x4f, 0xf2, 0xaf, 0x94, 0x9d, 0xb4, 0x9a, 0x22, 0xf4, 0xf6, 0xcd, 0x37, 0xc3, 0xf7,
	0xfd, 0x92, 0x05, 0x58, 0x12, 0x99, 0x69, 0x63, 0xd6, 0x76, 0x8d, 0xa1, 0xd3, 0x32, 0x86, 0xe8,
	0xa9, 0x6a, 0x6c, 0x27, 0x5f, 0x20, 0xbc, 0x27, 0x32, 0x78, 0x02, 0xbe, 0x56, 0xc2, 0x4b, 0xbd,
	0x2c, 0xc8, 0x7d, 0xad, 0xf0, 0x0c, 0x40, 0x19, 0x5d, 0xbf, 0x2f, 0x54, 0x61, 0x49, 0xf8, 0xec,
	0x27, 0xec, 0x3c, 0x16, 0x96, 0x10, 0x21, 0x6c, 0xf5, 0x17, 0x89, 0x20, 0xf5, 0xb2, 0x24, 0x67,
	0x2d, 0x6f, 0x61, 0xfc, 0x40, 0xab, 0x55, 0x61, 0xdc, 0xb6, 0x2e, 0x2a, 0xe2, 0xb8, 0x24, 0x67,
	0x8d, 0x29, 0x44, 0xae, 0xb9, 0x15, 0x7e, 0x1a, 0x64, 0x87, 0x33, 0x98, 0x32, 0x93, 0xeb, 0xce,
	0xfb, 0x85, 0xfc, 0xf6, 0x00, 0xdc, 0xbc, 0x27, 0x64, 0x02, 0x07, 0x6d, 0x57, 0x97, 0x6f, 0xba,
	0xda, 0x32, 0xfd, 0xce, 0x78, 0x0e, 0xf0, 0x51, 0xdb, 0xa2, 0x69, 0xd4, 0x2b, 0x75, 0x1b, 0xb0,
	0x81, 0x83, 0x97, 0x70, 0xbc, 0x99, 0xe6, 0x54, 0x1a, 0xb2, 0x22, 0xe4, 0x93, 0x5d, 0x13, 0xaf,
	0x21, 0x2e, 0xb9, 0xbf, 0x15, 0x11, 0x83, 0x1e, 0xf5, 0xa0, 0x3d, 0x54, 0xbe, 0x5d, 0xce, 0x16,
	0x70, 0xfa, 0xc7, 0x3a, 0x27, 0xf3, 0xa9, 0x4b, 0xc2, 0x2b, 0x88, 0xef, 0x94, 0xe2, 0xff, 0x39,
	0xf8, 0xbe, 0xc9, 0x4e, 0x84, 0x1c, 0xe1, 0x05, 0xc4, 0xcf, 0x64, 0xff, 0x9d, 0x0d, 0xb4, 0x1c,
	0x2d, 0xc7, 0xfc, 0x5c, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xb7, 0xe5, 0xf3, 0xbc,
	0x01, 0x00, 0x00,
}
